apiVersion: v1
kind: ConfigMap
metadata:
  name: pathofbackend
data:
  REACT_APP_API_URL : "https://31439-port-272041cac8e642f0.labs.kodekloud.com/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: combined
  template:
    metadata:
      labels:
        app: combined
    spec:
      containers:
      - name: combined
        image: yagami6/combinedsmallimage:v1
        ports:
        - name: frontend
          containerPort: 3000
        - name: backend
          containerPort: 4000
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        envFrom:
         - configMapRef:
            name: pathofbackend